import type { SiteSettings } from './types';

/*
 * The header/footer content exactly as it was on the static site. Used until
 * a "Site Settings" document exists in Sanity, and as the import seed for it.
 */
export const defaultSettings: SiteSettings = {
  logo: '/assets/images/Reviva_logo_.webp',
  logoAlt: 'Reviva Skin & Surgery Clinic',
  callDisplay: '78274 48711',
  callTel: '+917827448711',
  bookUrl: '/contact',
  nav: [
    { label: 'Home', href: '/' },
    { label: 'About', href: '/about' },
    {
      label: 'Treatments',
      columns: [
        {
          title: 'Signature',
          description: 'Our most requested non-surgical lifting protocols.',
          feature: true,
          links: [
            { label: 'Non-Surgical Face Lift (HIFU)', href: '/hifu-face-lift' },
            { label: 'RF Face Tightening', href: '/rf-face-tightening' },
            { label: 'Thread Lift', href: '/thread-lift' },
          ],
        },
        {
          title: 'Laser',
          links: [
            { label: 'Laser Hair Reduction', href: '/laser-hair-reduction' },
            { label: 'Laser for Pigmentation', href: '/laser-for-pigmentation' },
            { label: 'Birth Mark Removal', href: '/birth-mark' },
            { label: 'Tattoo Removal', href: '/tattoo' },
            { label: 'Stretch Marks', href: '/stretch-marks' },
            { label: 'Acne Scars', href: '/acne-scars' },
            { label: 'Freckles', href: '/freckles' },
            { label: 'Mole / Wart / Skin Tag', href: '/skin-tag' },
          ],
        },
        {
          title: 'Skin',
          links: [
            { label: 'Acne', href: '/acne-treatment' },
            { label: 'Melasma', href: '/melasma-treatment' },
            { label: 'Pigmentation', href: '/pigmentation-treatment' },
            { label: 'Dark Circles', href: '/dark-circles-treatment' },
            { label: 'Dark Lips', href: '/dark-lips-treatment' },
            { label: 'Body Polishing', href: '/body-polishing' },
            { label: 'Skin Brightening', href: '/skin-brightening' },
            { label: 'Eyebrows Microblading', href: '/eyebrows-microblading' },
          ],
        },
        {
          title: 'Hair',
          links: [
            { label: 'GFC Therapy', href: '/gfc-therapy' },
            { label: 'DUTEXOME Mesotherapy', href: '/dutexome-mesotherapy' },
            { label: 'Growth Factors Mesotherapy', href: '/growth-factors-mesotherapy' },
            { label: 'Hair Transplant', href: '/hair-transplant' },
            { label: 'Alopecia Treatment', href: '/alopecia-treatment' },
            { label: 'Female Hair Thinning', href: '/female-hair-thinning' },
          ],
        },
        {
          title: 'Medi Facials',
          links: [
            { label: 'Hydrafacial', href: '/hydra-facial' },
            { label: 'Oxygeneo Facial', href: '/oxygeneo-facial' },
            { label: 'Fire & Ice Facial', href: '/fire-and-ice-facial' },
            { label: 'PRX Plus Treatment', href: '/prx-plus-treatment' },
            { label: 'Lumiere Glow Ritual', href: '/lumiere-glow-ritual' },
            { label: 'Reviva Glow Infusion', href: '/reviva-glow-infusion' },
          ],
        },
        {
          title: 'Injectables',
          links: [
            { label: 'Under Eye Fillers', href: '/under-eye-fillers' },
            { label: 'Jawline Enhancement', href: '/jawline-enhancement' },
            { label: 'Face Lift with Fillers', href: '/face-lift-fillers' },
            { label: 'Cheek Enhancement', href: '/cheek-enhancement' },
            { label: 'Lip Fillers', href: '/lip-fillers' },
            { label: 'Non-Surgical Rhinoplasty', href: '/non-surgical-rhinoplasty' },
            { label: 'Double Chin Reduction', href: '/double-chin-reduction' },
            { label: 'Neck Lines', href: '/neck-lines-treatment' },
            { label: 'Wrinkle Reduction', href: '/wrinkle-reduction' },
          ],
        },
        {
          title: 'Dermatosurgery',
          links: [
            { label: 'Xanthelasma Removal', href: '/xanthelasma-removal' },
            { label: 'Earlobe Repair', href: '/earlobe-repair' },
            { label: 'Scar Excision', href: '/scar-excision' },
          ],
        },
      ],
    },
    { label: 'Results', href: '/gallery' },
    { label: 'Reviews', href: '/reviews' },
    { label: 'Blog', href: '/blogs' },
    { label: 'Contact', href: '/contact' },
  ],
  footerBlurb:
    'Premium dermatology, cosmetology and aesthetic surgery in Raj Nagar Extension,\n          Ghaziabad and Sector 76, Noida — where science meets skin.',
  social: { facebook: '#', instagram: '#', youtube: '#', x: '#' },
  footerTreatments: [
    { label: 'Non-Surgical Face Lift', href: '/hifu-face-lift' },
    { label: 'Laser Hair Reduction', href: '/laser-hair-reduction' },
    { label: 'Acne Treatment', href: '/acne-treatment' },
    { label: 'Pigmentation', href: '/pigmentation-treatment' },
    { label: 'Hair Transplant', href: '/hair-transplant' },
    { label: 'Fillers & Injectables', href: '/under-eye-fillers' },
    { label: 'Medi Facials', href: '/medi-facials' },
    { label: 'View All Treatments', href: '/treatment' },
  ],
  footerClinic: [
    { label: 'About Us', href: '/about' },
    { label: 'Results Gallery', href: '/gallery' },
    { label: 'Patient Reviews', href: '/reviews' },
    { label: 'Blog', href: '/blogs' },
    { label: 'Ghaziabad Clinic', href: '/ghaziabad' },
    { label: 'Noida Clinic', href: '/noida' },
    { label: 'Contact', href: '/contact' },
  ],
  locations: [
    {
      name: 'Ghaziabad',
      address: 'Quantum Homes, Raj Nagar Extension, Ghaziabad, Uttar Pradesh 201017',
      phoneDisplay: '+91 78274 48711',
      phoneTel: '+917827448711',
    },
    {
      name: 'Noida',
      address: 'Amrapali Silicon City, Gate No.-4, Sector-76, Noida',
      phoneDisplay: '+91 85958 56844',
      phoneTel: '+918595856844',
    },
  ],
  email: 'revivaskinandsurgery@gmail.com',
  hours: 'Mon–Sat: 11:00 AM – 1:00 PM, 5:00 PM – 7:30 PM',
  legal: [
    { label: 'Privacy Policy', href: '/privacy' },
    { label: 'Cookie Policy', href: '/cookie' },
    { label: 'No Refund Policy', href: '/norefundpolicy' },
    { label: 'Patient Data Protection', href: '/patientdata' },
    { label: 'Treatment Disclaimer', href: '/treatmentdisclaimer' },
    { label: 'Site Map', href: '/sitemap' },
  ],
  bookLabel: 'Book Now',
  bookLabelShort: 'Book',
  footerHeadings: { treatments: 'Treatments', clinic: 'Clinic', visit: 'Visit Us', hours: 'Clinic Hours' },
  copyright: 'Reviva Skin & Surgery Clinic. All rights reserved.',
  notFound: { eyebrow: '404', title: 'This page could not be found', buttonLabel: 'Back to home', buttonHref: '/' },
  whatsappUrl: 'https://wa.me/917827448711',
  postCta: {
    eyebrow: 'Book a consultation',
    title: 'Speak to Dr. Aarushi Tyagi’s team',
    text: 'Call the clinic nearest you to book a visit, or to ask about the treatment you have just read about.',
    altText: 'Prefer to write?',
    whatsappLabel: 'Message us on WhatsApp',
    whatsappHref: 'https://wa.me/917827448711',
    bookLabel: 'book online',
    bookHref: '/contact',
  },
  blogSidebar: {
    treatmentsTitle: 'Popular Treatments',
    treatments: [
      { label: 'Laser Hair Reduction', href: '/laser-hair-reduction' },
      { label: 'Acne Treatment', href: '/acne-treatment' },
      { label: 'Pigmentation', href: '/pigmentation-treatment' },
      { label: 'Melasma', href: '/melasma-treatment' },
      { label: 'Hair Transplant', href: '/hair-transplant' },
      { label: 'HIFU Face Lift', href: '/hifu-face-lift' },
      { label: 'Thread Lift', href: '/thread-lift' },
      { label: 'Under Eye Fillers', href: '/under-eye-fillers' },
    ],
    ctaEyebrow: 'Consultation',
    ctaTitle: 'Not sure which treatment you need?',
    ctaText: 'Dr. Aarushi Tyagi reviews your skin and hair concerns in person and builds a plan around them.',
    ctaButtonLabel: 'Book an appointment',
    ctaButtonHref: '/contact',
  },
};
